# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S9cQyONlPAaueoViWNhS8H5HlXqNrWyO
"""

data1 = {
    "deviceID": "dh28dslkja",
    "deviceType": "LaserCutter",
    "timestamp": 1624445837783,
    "location": "japan/tokyo/keiyō-industrial-zone/daikibo-factory-meiyo/section-1",
    "operationStatus": "healthy",
    "temp": 22
}

import json

with open("data-1.json", "w") as f:
    json.dump(data1, f)

data2 = {
    "device": {
        "id": "dh28dslkja",
        "type": "LaserCutter"
    },
    "timestamp": "2021-06-23T10:57:17.783Z",
    "country": "japan",
    "city": "tokyo",
    "area": "keiyō-industrial-zone",
    "factory": "daikibo-factory-meiyo",
    "section": "section-1",
    "data": {
        "status": "healthy",
        "temperature": 22
    }
}

import json

with open("data-2.json", "w") as f:
    json.dump(data2, f)

import json
from datetime import datetime

def convertFromFormat1(jsonObject):

    loc = jsonObject["location"].split("/")

    result = {
        "deviceID": jsonObject["deviceID"],
        "deviceType": jsonObject["deviceType"],
        "timestamp": jsonObject["timestamp"],
        "location": {
            "country": loc[0],
            "city": loc[1],
            "area": loc[2],
            "factory": loc[3],
            "section": loc[4]
        },
        "data": {
            "status": jsonObject["operationStatus"],
            "temperature": jsonObject["temp"]
        }
    }

    return result


def convertFromFormat2(jsonObject):

    dt = datetime.fromisoformat(jsonObject["timestamp"].replace("Z","+00:00"))
    millis = int(dt.timestamp()*1000)

    result = {
        "deviceID": jsonObject["device"]["id"],
        "deviceType": jsonObject["device"]["type"],
        "timestamp": millis,
        "location": {
            "country": jsonObject["country"],
            "city": jsonObject["city"],
            "area": jsonObject["area"],
            "factory": jsonObject["factory"],
            "section": jsonObject["section"]
        },
        "data": {
            "status": jsonObject["data"]["status"],
            "temperature": jsonObject["data"]["temperature"]
        }
    }

    return result


with open("data-1.json") as f:
    data1 = json.load(f)

with open("data-2.json") as f:
    data2 = json.load(f)

print(json.dumps(convertFromFormat1(data1), indent=4))
print(json.dumps(convertFromFormat2(data2), indent=4))

result = convertFromFormat2(data2)   # ya convertFromFormat1(data1)

import json

with open("data-result.json", "w") as f:
    json.dump(result, f, indent=4)

result1 = convertFromFormat1(data1)
result2 = convertFromFormat2(data2)

with open("result-format1.json","w") as f:
    json.dump(result1,f,indent=4)

with open("result-format2.json","w") as f:
    json.dump(result2,f,indent=4)

from google.colab import files
files.download("data-result.json")

import json
from datetime import datetime


# -------- Convert Format 1 --------
def convertFromFormat1(jsonObject):

    loc = jsonObject["location"].split("/")

    result = {
        "deviceID": jsonObject["deviceID"],
        "deviceType": jsonObject["deviceType"],
        "timestamp": jsonObject["timestamp"],
        "location": {
            "country": loc[0],
            "city": loc[1],
            "area": loc[2],
            "factory": loc[3],
            "section": loc[4]
        },
        "data": {
            "status": jsonObject["operationStatus"],
            "temperature": jsonObject["temp"]
        }
    }

    return result


# -------- Convert Format 2 --------
def convertFromFormat2(jsonObject):

    dt = datetime.fromisoformat(jsonObject["timestamp"].replace("Z", "+00:00"))
    millis = int(dt.timestamp() * 1000)

    result = {
        "deviceID": jsonObject["device"]["id"],
        "deviceType": jsonObject["device"]["type"],
        "timestamp": millis,
        "location": {
            "country": jsonObject["country"],
            "city": jsonObject["city"],
            "area": jsonObject["area"],
            "factory": jsonObject["factory"],
            "section": jsonObject["section"]
        },
        "data": {
            "status": jsonObject["data"]["status"],
            "temperature": jsonObject["data"]["temperature"]
        }
    }

    return result


# -------- Load Files --------
with open("data-1.json") as f:
    data1 = json.load(f)

with open("data-2.json") as f:
    data2 = json.load(f)

with open("data-result.json") as f:
    expected = json.load(f)


# -------- Run Conversions --------
result1 = convertFromFormat1(data1)
result2 = convertFromFormat2(data2)


# -------- Test Results --------
if result1 == expected and result2 == expected:
    print("All tests passed")
else:
    print("Test failed")

